[pytest]
python_files = Test_*.py
addopts =
    --alluredir=allure-results
    --html=reports/report.html
    --self-contained-html

markers =
    blocker: Highest priority tests
    critical: Critical priority tests
    normal: Normal priority tests
    minor: Minor priority tests
    trivial: least priority tests

